name: Trigger reusable workflow
env:
  env1: "An environment variable in caller"
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-reuse-workflow:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      input1: "This-is-input-1-from-caller-workflow"
    secrets:
      secret1: ${{ secrets.secret1 }}

  run-failed-reuse-workflow:
    uses: ./.github/workflows/failed-reuse-workflow.yml
  
  show-output-from-reuse-workflow:
    runs-on: ubuntu-latest
    needs: run-reuse-workflow
    steps:
      - name: Print single-line output
        run: echo '${{needs.run-reuse-workflow.outputs.reuse-workflow-out1}}'
      - name: Print multi-line output
        run: echo '${{needs.run-reuse-workflow.outputs.reuse-workflow-out2}}'